# Generated by Django 3.0.1 on 2020-01-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarAutoPilots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopilot_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'car_auto_pilot',
            },
        ),
        migrations.CreateModel(
            name='CarColorPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'car_color_prices',
            },
        ),
        migrations.CreateModel(
            name='CarColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('img_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'car_colors',
            },
        ),
        migrations.CreateModel(
            name='CarInteriorPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descriptions', models.CharField(max_length=3000)),
            ],
            options={
                'db_table': 'car_interior_prices',
            },
        ),
        migrations.CreateModel(
            name='CarInteriors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior_en_name', models.CharField(max_length=50)),
                ('interior_ko_name', models.CharField(max_length=50)),
                ('img_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'car_interiors',
            },
        ),
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('car_colors', models.ManyToManyField(through='price.CarColorPrices', to='price.CarColors')),
                ('car_interior', models.ManyToManyField(through='price.CarInteriorPrices', to='price.CarInteriors')),
            ],
            options={
                'db_table': 'car_models',
            },
        ),
        migrations.CreateModel(
            name='CarPaymentOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
                ('month', models.IntegerField()),
            ],
            options={
                'db_table': 'car_payment_option',
            },
        ),
        migrations.CreateModel(
            name='CarSeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'car_seats',
            },
        ),
        migrations.CreateModel(
            name='CarTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'car_types',
            },
        ),
        migrations.CreateModel(
            name='CarWheels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_name', models.CharField(max_length=50)),
                ('img_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'car_wheels',
            },
        ),
        migrations.CreateModel(
            name='CarWheelPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarModels')),
                ('wheel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarWheels')),
            ],
            options={
                'db_table': 'car_wheel_prices',
            },
        ),
        migrations.CreateModel(
            name='CarTypePrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('acceleration', models.DecimalField(decimal_places=1, max_digits=6)),
                ('fuel_economy', models.DecimalField(decimal_places=0, max_digits=6)),
                ('max_speed', models.DecimalField(decimal_places=0, max_digits=6)),
                ('wheel', models.CharField(max_length=200)),
                ('included_options', models.CharField(max_length=200)),
                ('img_url', models.URLField(max_length=2000)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarModels')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarTypes')),
            ],
            options={
                'db_table': 'car_type_prices',
            },
        ),
        migrations.CreateModel(
            name='CarSeatPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarModels')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarSeats')),
            ],
            options={
                'db_table': 'car_seat_prices',
            },
        ),
        migrations.CreateModel(
            name='CarOrderPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('saving_price', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('autopilot_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarAutoPilots')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarColors')),
                ('interior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarInteriors')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarModels')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarPaymentOptions')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarSeats')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarTypes')),
                ('wheel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarWheels')),
            ],
            options={
                'db_table': 'car_order_prices',
            },
        ),
        migrations.AddField(
            model_name='carmodels',
            name='car_seats',
            field=models.ManyToManyField(through='price.CarSeatPrices', to='price.CarSeats'),
        ),
        migrations.AddField(
            model_name='carmodels',
            name='car_types',
            field=models.ManyToManyField(through='price.CarTypePrices', to='price.CarTypes'),
        ),
        migrations.AddField(
            model_name='carmodels',
            name='car_wheels',
            field=models.ManyToManyField(through='price.CarWheelPrices', to='price.CarWheels'),
        ),
        migrations.AddField(
            model_name='carinteriorprices',
            name='interior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarInteriors'),
        ),
        migrations.AddField(
            model_name='carinteriorprices',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarModels'),
        ),
        migrations.AddField(
            model_name='carcolorprices',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarColors'),
        ),
        migrations.AddField(
            model_name='carcolorprices',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.CarModels'),
        ),
    ]
