# Generated by Django 3.0.1 on 2019-12-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'car_models',
            },
        ),
        migrations.CreateModel(
            name='CarTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'car_types',
            },
        ),
        migrations.CreateModel(
            name='CarTypePrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_price', models.DecimalField(decimal_places=8, max_digits=10)),
                ('model_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_models', to='price.CarModels')),
                ('type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_types', to='price.CarTypes')),
            ],
            options={
                'db_table': 'car_type_prices',
            },
        ),
        migrations.AddField(
            model_name='carmodels',
            name='car_types',
            field=models.ManyToManyField(related_name='car_models', through='price.CarTypePrices', to='price.CarTypes'),
        ),
    ]
