import first_input_car_models_1

import second_input_car_types_table_from_car_type_csv_2

import third_input_car_type_price_3

import fourth_input_car_colors_table_from_car_colors_csv_4

import fifth_input_car_color_price_from_current_tables_5

import sixth_input_car_wheels_6

import seventh_input_car_wheel_price_7

import eighth_input_car_interior_8

import nineth_input_car_interior_prices_9


import tenth_input_car_seats_10

import eleventh_input_car_seat_price_11

import twelveth_input_car_payment_options_12

import thirteenth_input_car_autopilot_options_13


import twentith_input_car_order_prices_20